# Inventory для деплоя Redmine на Timeweb Cloud VPS
# Перед запуском заменить ansible_host на реальный IP сервера

[redmine]
redmine-server ansible_host=5.42.124.174

[redmine:vars]
ansible_user=root
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'
